name: Update CWA Weather Data

on:
  schedule:
    - cron: "*/30 * * * *"  # 每 30 分鐘執行
  workflow_dispatch:  # 允許手動觸發

jobs:
  update_weather:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Python script to fetch weather data
      env:
        CWA_API_KEY: ${{ secrets.CWA_API_KEY }}  # 使用 GitHub Secrets
        GH_TOKEN: ${{ secrets.GH_TOKEN }}  # 使用 Personal Access Token
      run: |
        python keelung_getdata.py

    - name: Commit and push updated data
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add data/keelung_data.json
        git commit -m "更新 CWA 氣象署數據"
        git push https://github.com/${{ github.repository }}.git HEAD:main
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}  # 使用 GitHub Secrets 中的 Token
