name: Update CWA Weather Data

on:
  schedule:
    - cron: '0 * * * *'  # 每小時執行一次
  workflow_dispatch:  # 允許手動觸發工作流程

jobs:
  update_weather:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the repository
    - name: Check out the repository
      uses: actions/checkout@v4  # 更新到最新版本

    # 2. Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v5  # 更新到最新版本
      with:
        python-version: '3.11'  # 指定具體版本，避免模糊的 '3.x'

    # 3. Install required dependencies
    - name: Install dependencies
      run: |
        pip install requests pytz  # 只安裝必要的依賴

    # 4. Run the Python script to fetch weather data
    - name: Run Python script to fetch weather data
      env:
        CWA_API_KEY: ${{ secrets.CWA_API_KEY }}  # 使用 GitHub Secrets 中的 API Key
      run: |
        python keelung_getdata.py

    # 5. Commit and push updated data
    - name: Commit and push updated data
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add data/keelung_data.json
        git commit -m "更新 CWA 氣象署數據: $(date -u +'%Y-%m-%d %H:%M:%S UTC')" || echo "No changes to commit"
        git push
