name: Update CWA Weather Data

on:
  schedule:
    - cron: '0 * * * *'  # 每小時執行一次
  workflow_dispatch:  # 允許手動觸發工作流程

jobs:
  update_weather:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}  # 明確使用 GITHUB_TOKEN

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install requests pytz

    - name: Run Python script to fetch weather data
      env:
        CWA_API_KEY: ${{ secrets.CWA_API_KEY }}
      run: |
        python keelung_getdata.py

    - name: Commit and push updated data
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add data/keelung_data.json
        git commit -m "更新 CWA 氣象署數據: $(date -u +'%Y-%m-%d %H:%M:%S UTC')" || echo "No changes to commit"
        git push
